update
tap homebrew/dupes

install gcc48
install openssl
install git
install vim --override-system-vi --with-python3 --with-client-server
install tmux
install reattach-to-user-namespace
install zsh
install grc
install the_silver_searcher
install nginx
install node
install mongodb
install hub
install pow
install rbenv
install rbenv-gem-rehash
install ruby-build
install rbenv-default-gems
